/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiYoutubeRouteImport } from './routes/api/youtube'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiSttRouteImport } from './routes/api/stt'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedPersonalityRouteImport } from './routes/_authenticated/personality'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedDayTurnoverRouteImport } from './routes/_authenticated/day-turnover'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as ApiPublicBiometricsRouteImport } from './routes/api/public/biometrics'
import { Route as ApiHealthAiRouteImport } from './routes/api/health.ai'
import { Route as ApiDebugLastPromptRouteImport } from './routes/api/debug.last-prompt'
import { Route as AuthenticatedCThreadIdRouteImport } from './routes/_authenticated/c.$threadId'
import { Route as ApiPublicHooksProcessChatJobsRouteImport } from './routes/api/public/hooks/process-chat-jobs'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiYoutubeRoute = ApiYoutubeRouteImport.update({
  id: '/api/youtube',
  path: '/api/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSttRoute = ApiSttRouteImport.update({
  id: '/api/stt',
  path: '/api/stt',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonalityRoute =
  AuthenticatedPersonalityRouteImport.update({
    id: '/personality',
    path: '/personality',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDayTurnoverRoute =
  AuthenticatedDayTurnoverRouteImport.update({
    id: '/day-turnover',
    path: '/day-turnover',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicBiometricsRoute = ApiPublicBiometricsRouteImport.update({
  id: '/api/public/biometrics',
  path: '/api/public/biometrics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthAiRoute = ApiHealthAiRouteImport.update({
  id: '/api/health/ai',
  path: '/api/health/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugLastPromptRoute = ApiDebugLastPromptRouteImport.update({
  id: '/api/debug/last-prompt',
  path: '/api/debug/last-prompt',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCThreadIdRoute = AuthenticatedCThreadIdRouteImport.update({
  id: '/c/$threadId',
  path: '/c/$threadId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicHooksProcessChatJobsRoute =
  ApiPublicHooksProcessChatJobsRouteImport.update({
    id: '/api/public/hooks/process-chat-jobs',
    path: '/api/public/hooks/process-chat-jobs',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/day-turnover': typeof AuthenticatedDayTurnoverRoute
  '/events': typeof AuthenticatedEventsRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/personality': typeof AuthenticatedPersonalityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/chat': typeof ApiChatRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/youtube': typeof ApiYoutubeRoute
  '/c/$threadId': typeof AuthenticatedCThreadIdRoute
  '/api/debug/last-prompt': typeof ApiDebugLastPromptRoute
  '/api/health/ai': typeof ApiHealthAiRoute
  '/api/public/biometrics': typeof ApiPublicBiometricsRoute
  '/api/public/hooks/process-chat-jobs': typeof ApiPublicHooksProcessChatJobsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRoute
  '/day-turnover': typeof AuthenticatedDayTurnoverRoute
  '/events': typeof AuthenticatedEventsRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/personality': typeof AuthenticatedPersonalityRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/api/chat': typeof ApiChatRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/youtube': typeof ApiYoutubeRoute
  '/c/$threadId': typeof AuthenticatedCThreadIdRoute
  '/api/debug/last-prompt': typeof ApiDebugLastPromptRoute
  '/api/health/ai': typeof ApiHealthAiRoute
  '/api/public/biometrics': typeof ApiPublicBiometricsRoute
  '/api/public/hooks/process-chat-jobs': typeof ApiPublicHooksProcessChatJobsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRoute
  '/_authenticated/day-turnover': typeof AuthenticatedDayTurnoverRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/personality': typeof AuthenticatedPersonalityRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/api/chat': typeof ApiChatRoute
  '/api/stt': typeof ApiSttRoute
  '/api/tts': typeof ApiTtsRoute
  '/api/youtube': typeof ApiYoutubeRoute
  '/_authenticated/c/$threadId': typeof AuthenticatedCThreadIdRoute
  '/api/debug/last-prompt': typeof ApiDebugLastPromptRoute
  '/api/health/ai': typeof ApiHealthAiRoute
  '/api/public/biometrics': typeof ApiPublicBiometricsRoute
  '/api/public/hooks/process-chat-jobs': typeof ApiPublicHooksProcessChatJobsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/app'
    | '/day-turnover'
    | '/events'
    | '/library'
    | '/personality'
    | '/settings'
    | '/tasks'
    | '/api/chat'
    | '/api/stt'
    | '/api/tts'
    | '/api/youtube'
    | '/c/$threadId'
    | '/api/debug/last-prompt'
    | '/api/health/ai'
    | '/api/public/biometrics'
    | '/api/public/hooks/process-chat-jobs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/app'
    | '/day-turnover'
    | '/events'
    | '/library'
    | '/personality'
    | '/settings'
    | '/tasks'
    | '/api/chat'
    | '/api/stt'
    | '/api/tts'
    | '/api/youtube'
    | '/c/$threadId'
    | '/api/debug/last-prompt'
    | '/api/health/ai'
    | '/api/public/biometrics'
    | '/api/public/hooks/process-chat-jobs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/day-turnover'
    | '/_authenticated/events'
    | '/_authenticated/library'
    | '/_authenticated/personality'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/api/chat'
    | '/api/stt'
    | '/api/tts'
    | '/api/youtube'
    | '/_authenticated/c/$threadId'
    | '/api/debug/last-prompt'
    | '/api/health/ai'
    | '/api/public/biometrics'
    | '/api/public/hooks/process-chat-jobs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSttRoute: typeof ApiSttRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiYoutubeRoute: typeof ApiYoutubeRoute
  ApiDebugLastPromptRoute: typeof ApiDebugLastPromptRoute
  ApiHealthAiRoute: typeof ApiHealthAiRoute
  ApiPublicBiometricsRoute: typeof ApiPublicBiometricsRoute
  ApiPublicHooksProcessChatJobsRoute: typeof ApiPublicHooksProcessChatJobsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/youtube': {
      id: '/api/youtube'
      path: '/api/youtube'
      fullPath: '/api/youtube'
      preLoaderRoute: typeof ApiYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stt': {
      id: '/api/stt'
      path: '/api/stt'
      fullPath: '/api/stt'
      preLoaderRoute: typeof ApiSttRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personality': {
      id: '/_authenticated/personality'
      path: '/personality'
      fullPath: '/personality'
      preLoaderRoute: typeof AuthenticatedPersonalityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/day-turnover': {
      id: '/_authenticated/day-turnover'
      path: '/day-turnover'
      fullPath: '/day-turnover'
      preLoaderRoute: typeof AuthenticatedDayTurnoverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/biometrics': {
      id: '/api/public/biometrics'
      path: '/api/public/biometrics'
      fullPath: '/api/public/biometrics'
      preLoaderRoute: typeof ApiPublicBiometricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/ai': {
      id: '/api/health/ai'
      path: '/api/health/ai'
      fullPath: '/api/health/ai'
      preLoaderRoute: typeof ApiHealthAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug/last-prompt': {
      id: '/api/debug/last-prompt'
      path: '/api/debug/last-prompt'
      fullPath: '/api/debug/last-prompt'
      preLoaderRoute: typeof ApiDebugLastPromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/c/$threadId': {
      id: '/_authenticated/c/$threadId'
      path: '/c/$threadId'
      fullPath: '/c/$threadId'
      preLoaderRoute: typeof AuthenticatedCThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/process-chat-jobs': {
      id: '/api/public/hooks/process-chat-jobs'
      path: '/api/public/hooks/process-chat-jobs'
      fullPath: '/api/public/hooks/process-chat-jobs'
      preLoaderRoute: typeof ApiPublicHooksProcessChatJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRoute
  AuthenticatedDayTurnoverRoute: typeof AuthenticatedDayTurnoverRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedPersonalityRoute: typeof AuthenticatedPersonalityRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedCThreadIdRoute: typeof AuthenticatedCThreadIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRoute,
  AuthenticatedDayTurnoverRoute: AuthenticatedDayTurnoverRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedPersonalityRoute: AuthenticatedPersonalityRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedCThreadIdRoute: AuthenticatedCThreadIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSttRoute: ApiSttRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiYoutubeRoute: ApiYoutubeRoute,
  ApiDebugLastPromptRoute: ApiDebugLastPromptRoute,
  ApiHealthAiRoute: ApiHealthAiRoute,
  ApiPublicBiometricsRoute: ApiPublicBiometricsRoute,
  ApiPublicHooksProcessChatJobsRoute: ApiPublicHooksProcessChatJobsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
